name:                TorrentFuse
version:             0.0.0.1
github:              "Ofenhed/fuse.torrent"
license:             BSD3
author:              "Marcus Ofenhed"
copyright:           "2020 Marcus Ofenhed"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TorrentFuse#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- unix >= 2 && < 3
- filepath >= 1.4
- lens >= 4.18
- mtl >= 2 && < 3
- containers >= 0.6 && < 0.9
- directory >= 1.3 && < 2
- inline-c >= 0.9.1 && < 1
- inline-c-cpp >= 0.4.0.2 && < 0.6
- vector
- template-haskell >= 2.15
- optparse-applicative >= 0.18
- aeson >= 2.2

library:
  source-dirs:
  - src
  - clib
  cxx-options: -std=c++17
  include-dirs: clib/headers
  default-extensions: CPP
  # ghc-options:
  # - -Wall
  extra-libraries:
  - stdc++
  - torrent-rasterbar
  # - try_signal

executables:
  TorrentFuse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -g2
    - -Wall
    dependencies:
    - TorrentFuse
    - HFuse >= 0.2.5 && < 0.3

tests:
  TorrentFuse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TorrentFuse
